/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.sfhome.openremote.protocol.mc401.TestUtils;

import com.google.gwt.regexp.shared.RegExp;
//import org.gwtproject.regexp.shared.RegExp;

import java.lang.Exception;
import java.util.AbstractMap.SimpleEntry;
import java.util.Collections;
import java.util.function.BiConsumer;
import java.util.function.Consumer;
import java.util.function.Supplier;
import java.util.*;
import java.util.stream.*;
import java.util.stream.Collectors.*;


//import org.junit.Test;
//port org.junit.BeforeEach;

//import static org.junit.Assert.*;


import net.sfhome.openremote.protocol.mc401.*;

import org.openremote.model.attribute.AttributeRef;
import org.openremote.model.attribute.AttributeState;
import org.openremote.model.value.*;


public class ResponseFields {
    static private String[] resp1Fields = {"Energy", "Volume", "Hours", "T1", "T2", "T1_T2", "power", "Flow", "PeakPwrFlw", "Info"};
    static private String[] resp2Fields = {"CustNo2", "TA2", "TL2", "TA3", "TL3", "InA", "InB", "ABCCC", "DDEFFGG", "Date"};
    static private String[] resp3Fields = {"CustNo3", "ReadingDay", "EnergyInPeriod", "VolumeInPeriod", "TA2_Period", "TA3_Period", "InAInPeriod", "InBInPeriod", "PeakPwrFlwInPeriod"};

    /**
     * Method to get array of field in response of given request number
     * @param respNumber - number of request/response of which fields we want to get
     * @return array of strings containing field names in given response
     */
    static public String[] getResponseFields(int respNumber) throws IllegalArgumentException {
        if(respNumber < 1 || respNumber > 3) {
            throw new IllegalArgumentException(String.format("respNumber argument in UpdateMonitor creator needs to have value <1,3>, while is has value of %d\n", respNumber)); 
        }

        String[] responseFields;
        switch(respNumber) {
            case 1: 
                responseFields = resp1Fields;break;
            case 2:
                responseFields = resp2Fields;break;
            case 3:
                responseFields = resp3Fields;break;
            default:
                responseFields = new String[0];break;
        }      

        return responseFields;
    }

    /**
     * Method to find request/response number for which field belongs to
     * @param fieldName - name of the field in response
     * @return number of response/request
     */
    static public int findResponseNumber(String fieldName) {
       int foundResponseNumber = 0;
       for(int x = 1;x<4;x++) {
           if(Stream.of(getResponseFields(x)).filter(name -> name == fieldName).findFirst().isPresent()) //orNull() != NULL)
               foundResponseNumber = x;
       }

       return foundResponseNumber;       

    }
}




            
